import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTrasition from "@/components/StairTrasition";

const Jetbrains_Mono = JetBrains_Mono({ 
  subsets: ["latin"],
  Weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono"  
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Jetbrains_Mono.variable}>
        <Header/>
        <PageTransition >
          <StairTrasition />
          {children}
        </PageTransition>
        
      </body>
    </html>
  );
}
